notifications:
  email: false
language: node_js
cache:
  directories:
    - node_modules # Speed up npm install
node_js:
  - "5.10.0"
os:
  - linux
  - osx
env:
  global:
    - CXX=g++-4.8
osx_image: xcode7

matrix:
  include:
    - os: linux
      env: TARGET_ARCH=ia32
    - os: linux
      env: TARGET_ARCH=x64
  allow_failures:
    - os: osx
      env: TARGET_ARCH=x64
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
before_script:
  - npm install
  - if [[ "$TARGET_ARCH" == "x64" ]]; then npm run build:linux64; fi;
  - if [[ "$TARGET_ARCH" == "ia32" ]]; then npm run build:linux32; fi;
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run build:mac; fi;
  - zip -rq dist.zip dist
script: node build/upload.js
