language: node_js
cache:
  directories:
    - node_modules # Speed up npm install
node_js:
  - "5.10.0"
env:
  global:
    - CXX=g++-4.8
  matrix:
    - TRAVIS_NODE_VERSION="5"
    - TRAVIS_NODE_VERSION="5" ARCH="x86"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_script:
  - npm install
  - if [[ "$ARCH" == "x86" ]]; then
    npm run build:linux32;
    else npm run build:linux64;
    fi;

